# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
product_name: &product_name Engine
title: *product_name
email: degoodmanwilson@gmail.com
version: 1.0-beta26
description: >
  Connect with the Slack Platform in modern C++
# Build settings
markdown: kramdown
gems:
  - jemoji
